server:
  port: 8081

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  application:
    name: coupon-api

  profiles:
    include:
      - persistence

---
spring:
  config:
    activate:
      on-profile: local

