spring:
  application:
    name: coupon-redis-cache
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  serialization:
    write-dates-as-timestamps: false

---
spring:
  config:
    activate:
      on-profile: local
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 26379
      ttl: 300

---
spring:
  config:
    activate:
      on-profile: test

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 300
---

spring:
  config:
    activate:
      on-profile: docker
  cache:
    type: redis
  data:
    redis:
      host: local-redis
      port: 6379
      ttl: 300

---
