spring:
  application:
    name: coupon-kafka


  kafka:
    topics:
      coupon-download: coupon-download-request
    consumer:
      group-id: coupon-consumer
---

spring:
  config:
    activate:
      on-profile: local

---
