spring:
  application:
    name: coupon-consumer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
  serialization:
    write-dates-as-timestamps: false

  profiles:
    include:
      - persistence
      - redis
      - kafka

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 9004
  shutdown: graceful
