spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  application:
    name: coupon-persistence

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    out-of-order: true
    baseline-on-migrate: true
    locations:
      - "classpath:db/migration/coupon"
    defaultSchema: coupon
---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      max-lifetime: 250000 #250 sec
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    url: jdbc:mysql://localhost:23306/coupon?autoReconnect=true
    username: user
    password: user

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/coupon?autoReconnect=true
    username: user
    password: user

  flyway:
    enabled: false
